ALTER TABLE chama ADD COLUMN anchor_date DATE NOT NULL DEFAULT CURRENT_DATE, ADD COLUMN grace_period_days INT NOT NULL DEFAULT 3,
ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE, ADD COLUMN deleted_at TIMESTAMP DEFAULT NULL;

